global:
  scrape_interval: 15s
  evaluation_interval: 15s

storage:
  tsdb:
    retention.time: 15d

scrape_configs:
  - job_name: 'trustgate'
    static_configs:
      - targets: ['host.docker.internal:9090']